### ISSUE TITLE
Bootstrapping iwant fails: Server returned HTTP response code: 501 for URL: http://repo1.maven.org/maven2/org/apache/ant/ant/1.10.1/ant-1.10.1.jar

### ISSUE THREAD

**Issue by geirsandearm** [wipu/iwant#1]
Here's the stacktrace
`09:08:28 :     Downloading -> /home/jenkins/.org.fluentjava.iwant/cached/UnmodifiableUrl/https%3A/%2Fgithub.com/wipu/iwant/archive/f1daac5386eed098b183afe96c3f1338e7bdbb08.zip
09:08:28 :       Unzipping -> /home/jenkins/.org.fluentjava.iwant/cached/UnmodifiableZip/file%3A/home/jenkins/.org.fluentjava.iwant/cached/UnmodifiableUrl/https%25253A/%25252Fgithub.com/wipu/iwant/archive/f1daac5386eed098b183afe96c3f1338e7bdbb08.zip
09:08:28 :       Compiling -> /home/jenkins/.org.fluentjava.iwant/cached/ClassesFromUnmodifiableIwantEssential/%2Fhome/jenkins/.org.fluentjava.iwant/cached/UnmodifiableZip/file%253A/home/jenkins/.org.fluentjava.iwant/cached/UnmodifiableUrl/https%2525253A/%2525252Fgithub.com/wipu/iwant/archive/f1daac5386eed098b183afe96c3f1338e7bdbb08.zip/iwant-f1daac5386eed098b183afe96c3f1338e7bdbb08/essential
09:08:28 :     Downloading -> /home/jenkins/.org.fluentjava.iwant/cached/UnmodifiableUrl/http%3A/%2Frepo1.maven.org/maven2/org/apache/ant/ant/1.10.1/ant-1.10.1.jar
09:08:28 Exception in thread "main" java.lang.reflect.InvocationTargetException
09:08:28 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
09:08:28 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
09:08:28 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09:08:28 	at java.lang.reflect.Method.invoke(Method.java:498)
09:08:28 	at org.fluentjava.iwant.entry.Iwant.runJavaMain(Iwant.java:591)
09:08:28 	at org.fluentjava.iwant.entry.Iwant.evaluate(Iwant.java:265)
09:08:28 	at org.fluentjava.iwant.entry.Iwant.main(Iwant.java:231)
09:08:28 Caused by: java.lang.RuntimeException: java.io.IOException: Server returned HTTP response code: 501 for URL: http://repo1.maven.org/maven2/org/apache/ant/ant/1.10.1/ant-1.10.1.jar
09:08:28 	at org.fluentjava.iwant.entry.Iwant.downloaded(Iwant.java:762)
09:08:28 	at org.fluentjava.iwant.entry.Iwant.downloaded(Iwant.java:768)
09:08:28 	at org.fluentjava.iwant.entry2.Iwant2.antJar(Iwant2.java:123)
09:08:28 	at org.fluentjava.iwant.entry2.Iwant2.iwantBinDeps(Iwant2.java:108)
09:08:28 	at org.fluentjava.iwant.entry2.Iwant2.allIwantClasses(Iwant2.java:176)
09:08:28 	at org.fluentjava.iwant.entry2.Iwant2.evaluate(Iwant2.java:65)
09:08:28 	at org.fluentjava.iwant.entry2.Iwant2.main(Iwant2.java:50)
09:08:28 	... 7 more
09:08:28 Caused by: java.io.IOException: Server returned HTTP response code: 501 for URL: http://repo1.maven.org/maven2/org/apache/ant/ant/1.10.1/ant-1.10.1.jar
09:08:28 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
09:08:28 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
09:08:28 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
09:08:28 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
09:08:28 	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1926)
09:08:28 	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1921)
09:08:28 	at java.security.AccessController.doPrivileged(Native Method)
09:08:28 	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1920)
09:08:28 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1490)
09:08:28 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
09:08:28 	at org.fluentjava.iwant.entry.Iwant.downloadBytes(Iwant.java:785)
09:08:28 	at org.fluentjava.iwant.entry.Iwant.downloaded(Iwant.java:755)
09:08:28 	... 13 more
09:08:28 Caused by: java.io.IOException: Server returned HTTP response code: 501 for URL: http://repo1.maven.org/maven2/org/apache/ant/ant/1.10.1/ant-1.10.1.jar
09:08:28 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
09:08:28 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
09:08:28 	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
09:08:28 	at org.fluentjava.iwant.entry.Iwant.downloadBytes(Iwant.java:778)
09:08:28 	... 14 more`

With https the links are working:
https://repo1.maven.org/maven2/org/apache/ant/ant/1.10.1/ant-1.10.1.jar

**Comment by wipu** [comment]
Thanks for the report. I'll investigate.

**Comment by wipu** [comment]
Fixed in b92564df8bba8c19e856bffaead51c4ebb03a849: now using https instead of http in the default repo prefix.

**Comment by OPpuolitaival** [comment]
@wipu Did you try to fix? Some cases it still seems to try http url for fetching ant

**Comment by OPpuolitaival** [comment]
> @wipu Did you try to fix? Some cases it still seems to try http url for fetching ant

It seems that I have old version still in some places for some reason

**Comment by wipu** [comment]
Let me know if there are further complications. Note that you can also use the factory method FromRepository.at instead of the default FromRepository.repo1MavenOrg, for a custom url prefix.

**Comment by wipu** [comment]
(Funny: github closed this ticket automatically when I said "Fixed #1" in my git commit. I didn't mean that.)
